* Chapter 99
  Pi and the two interviewers debate on the validity of Pi's story regarding topics such as the floating bananas, algae island, tiger, meerkats. Pi ends up putting up quite the fight and strongly refutes their arguments, all the while gradually, and comedically, taking their lunch.
  
  Eventually, the two ask Pi for a story without animals that does have any "invention." Pi somewhat maliciously complies, crafting a fake story of how four people, his mother, a cook, a sailor, and him, managed to get onto the lifeboat. Pi tells a story full of drama with an evil cook and much bloodshed. Interestingly, however, the people in the story seem to bear a resemblance to some of the animals in Pi's original story.
  
  The two inquire more about the ship itself and what might have caused it to sink, but nothing is brought to light.
  
  Pi asks the two which story was better, to which they reply stating that they like the one with the animals better.
  
  Pi says that he will move on and go to Canada.
