* Characters
** George
   - Companions with Lennie
   - Looking for work in beginning
   - Holds some connection to Lennie (not family)
** Lennie
   - Had an Aunt named Clara
   - Has a mental disability
   - Causes problems for George
   - Likes soft things
   - Very attached to tending to rabbits
   - Very strong
   - Cannot control himself at times
   - Very forgetful
   - Depends on George
** Candy
   - Friendly to George and Lennie
   - Old
   - Had an sheep old dog
   - Wanted to join George and Lennie in buying land
** Crooks
   - Stable buck
   - Black
   - Lives alone in the harness room
   - Described as "proud and aloof"
   - Kept distance from others
   - Injured back
** Slim
   - Is a jerkline skinner
   - Well liked by everyone
   - Friendly and confident
   - Owns a working dog with puppies
** Carlson
   - Big figure
   - Owns a shotgun
   - Disliked Candy's dog
** Curley
   - Son of the ranch's boss
   - Temperamental; prone to fights
   - Strong
** Curley's Wife
   - Married only a couple of weeks to Curley
   - Described as "pretty"
   - Has "the eye"
   - Lonely
* Setting
  This novel is set around the late 1930s, during the Great Depression, near Soledad, California. At the start of the story, George and Lennie start near the Salinas River and make their way to work at a ranch.
* Chapter 1
** Section Focus
   John Steinbeck wrote as social commentary and wrote /Of Mice and Men/ to address several issues, including the plight of migrant workers, how society treats those with disabilities and women, and racism.

   In the exposition (beginning) of a story, the narrator often introduces the time, place, characters, and conflict.  As you read, consider how the characters might represent a social issue during this time period.
** Summary
   The story begins with our two main characters, George and Lennie, arriving at a pool of water on a trail. Lennie asks George where they are going, to which George responds in frustration at Lennie's poor memory. From this, the author hints that Lennie isn't very sharp and potentially might have a mental disability. After some banter, George reveals that they are heading to a ranch some distance ahead to work at. During the conversation, George notices that Lennie was carrying a dead mouse to pet. This paired along with his mention of rabbits earlier would suggest that Lennie is fond of soft, cute animals. After inquiring about the mouse, George asserts multiple times that Lennie should not talk at the ranch and let George do the explaining, alluding at an incident caused by Lennie in Weed. While preparing for dinner, George voices his disdain at traveling with Lennie and explains how easy life would be without him. Lennie, feeling guilty, asks George if he should leave. George realizes what he has said and convinces Lennie to calm down and not leave. At Lennie's request, George talks about "the rabbits," and explains their dream to live on their own land and provide for themselves by tending to animals and farming produce. After George is done telling the story, he reminds Lennie to not say a word at the ranch and tells him to come back to the place they are currently should they encounter any trouble. The chapter ends with both of them going to sleep.
* Chapter 2
** Section Focus
   In the exposition (beginning) of a story, the narrator often introduces the time, place, characters, and conflict. As you read, pay close attention to what you learn about the characters.
   
   It will be helpful to highlight important things about the characters and their relationships to each other. Consider using different note colors for characters and nothing their relationships to each other. Also consider how the characters might represent a social issue during this time period.
** Summary
   The chapter begins with George and Lennie entering the ranch. As they step in, they meet an old man who guides them to their beds. After some talk with the man, George and Lennie settle in. After a while, the boss of the ranch comes in to meet the group. After giving some information to the boss, Lennie talks, breaking his promise with George. The boss, noticing how little Lennie talks, grows a bit suspicious of George. After some more talk, the boss mentions Slim, the skinner, and leaves. George then scolds Lennie for breaking his promise of not talking. Afterwards, the old man comes back into the room with his very old sheep dog. Following the conversation with the old man, Curley, the son of the boss, enters the room. Curley talks coldly to George and confronts Lennie for not talking to him. Once Curley leaves the room, the old man tells George about him and his wife. From what is said, we learn that Curley is quite strong and temperamental. After their conversation, George warns Lennie not to engage with Curley and reminds him where to go if they get in trouble. Mid-conversation, Curley's wife arrives in the doorway, claiming to be looking for Curley. After a little conversation, Slim comes into the room and tells her where Curley was heading. Once she leaves, George warns Lennie not to go near her. Slim then welcomes George and Lennie and converses with them until another man named Carlson comes in. The conversation then shifts to Slim's dog, and eventually to the old man, who we now learn is named Candy, and his old sheep dog. Slim and Carlson then leave to go eat dinner, leaving George and Lennie alone once again. After a short while, Curley once again enters the room, inquiring where his wife is. Once George told Curley that he didn't know where she went, Curley hurriedly left.
* Chapter 3
** Section Focus
   In the rising action of a story, the conflict is established and tension builds.

   In this chapter, pay attention to how relationships between characters change and how those changes may cause conflict.
** Summary
   The chapter starts with George and Slim talking about Lennie. George explains his backstory regarding Lennie until Lennie enters the room, concealing a puppy near his stomach. Lennie then left the room after being instructed by George to return the puppy. Once Lennie leaves, Candy and his dog enter the room. Carlson also enters the room and expresses disgust at Candy's old dog, asking him to shoot it. At first, Candy is reluctant, but, after much convincing, Candy lets Carlson shoot his dog. After some small conversation, Crooks comes in the room and tells Slim that the tar is ready. Slim then leaves for the stable. Once Slim leaves, the group discuss Curley's wife and places in town, but the conversation is interrupted by Lennie and Carlson entering the room. Carlson relays that Curley is looking for his wife, and, conveniently, Curley bursts into the room for that same purpose. After Whit answers, Curley asks where Slim, suspecting that his wife may be there, is and is directed to the barn. Upon hearing the news, Curley leaves the room for the barn. Carlson and Whit also leave the room, leaving George, Lennie, and Candy alone. Following some discussion and a warning from George for Lennie not to get mixed up in fights, Lennie asks George to tell the story about their dream farm. Candy jumps in the conversation asking whether George actually knows a place like that. After hearing about the cost, Candy reveals that he would be willing to pitch in $350 for the permission to live with them. After some more discussion, the group found the goal much more realistic. In the middle of their discussion, however, they were interrupted by Curley, Slim, and Carlson entering the room while fighting. Curley, still angry from trying to pick a fight with Slim and failing, sees Lennie smiling and engages with him. After Curley injures Lennie's eye, George tells Lennie to fight Curley back. After catching Curley's fist and crushing his hand, George tells Lennie to stop, however Lennie loses control of himself. After a while, Lennie finally lets go of Curley's hands. After threatening Curley to not tell anyone what happen, Carlson takes Curley to a doctor. After reassuring Lennie that he didn't do anything wrong, the chapter ends.
* Chapter 4
** Section Focus
   In the rising action of a story, the conflict is established and tension builds.
   
   In this chapter, pay attention to how relationships between characters change and how those changes may cause conflict.
** Summary
   The chapter starts with an introduction to Crooks and the harness room that he lives in. After a detailed description of Crooks and his room is given, Lennie appears in the doorway of his room. Crooks treats Lennie coldly and tells him to leave. After some more conversation between the two, Crooks finally relents and lets Lennie in the room with a more friendly tone. Lennie explains that everyone else has went to town besides Candy. Lennie then talks about the dream farm that he promised to keep secret. After talking about his backstory, Crooks moves on to ask Lennie what he would do if George left. After Lennie freaks out, Crooks backs down and changes the topic. Candy then enters the room and asks for Lennie. Crooks then invites Candy into the room. Candy and Crooks debate about their dream farm and a chance at owning land. Then the group is interrupted by Curley's wife who is looking for Curley. The group talks with Curley's wife and the tension escalates until she asks about Curley's hand. They try to pass it off that Curley's hand got caught in a machine, however Curley's wife wouldn't believe them. They argue more and Curley's wife notices Lennie's bruised head. Once Crooks tells Curley's wife to leave, she threatens to get him in trouble, causing him to shrink back. After Candy tells her to leave, she talks to them some more and finally exits the room. George then arrives back from town and looks for Lennie. After some more discussion, everyone leaves the room, ending the chapter.
* Chapter 5
** Section Focus
   In the climax of a story, the conflict plays out, and change must happen.

   In this chapter, pay attention to how the conflict plays out and what happens as a result.
** Summary
   At the start of the chapter, we learn that Lennie is in the barn while the others are playing horseshoes. From further dialogue from Lennie, we can also tell that he killed his puppy that he was taking care of. Fearing getting in trouble, Lennie tries hiding the body. Then, as Lennie is carrying the puppys's body, Curley's wife comes in. Hurriedly, Lennie covers the body with hay. When Curley's wife tries to speak with Lennie, he tries to get away, remembering George's advice to stay away from her. Even after more conversation, Lennie refuses to talk to her. When Curley's wife asks about what he was doing, however, she realizes that he killed the puppy. When Lennie still tries to avoid Curley's wife, she becomes angry and rants for a while. When she asks Lennie about the rabbits and why he likes them so much, he responds by saying that he likes soft things. Curley's wife empathizes with him and even offers to let him touch her hair. Lennie obliges, but when she asks him to let go, he loses control again and grabs harder. When she starts screaming, Lennie grows even more angry, to the point where he shakes her around, breaking her neck and killing her. He then attempts to hide her body using hay. Recalling what George told him, Lennie sets off for the brush near the river to hide in and wait for George. After some time passes, George and Candy finish playing and return back inside, calling out for Lennie. When George and Candy encounter Curley's wife laying in the hay, they check her pulse and find out that she is dead. When asked what to do, George responds with uncertainty and states that he will take Lennie to jail. Candy rejects the idea, fearing Curley or the others would kill him instead. After some talk, they call off the idea of the dream farm. George directs Candy to tell the others what happened. When the others come in, Curley is furious and sets out to kill Lennie. Carlson also heads out and goes to get his shotgun. After talking with Slim, Carlson comes back and claims that Lennie stole his shotgun. Curley then asks Whit to get a sheriff. Although George attempts to calm Curley and ask him to not kill Lennie, he is unsuccessful. Curley tells Candy to stay with his wife and the others head off to find Lennie, concluding the chapter.
* Chapter 6
** Section Focus
   In the resolution of a story, the conflict is resolved and relationships often change.
   
   In this chapter, pay attention to how the conflict changes the relationship between George and Lennie.
** Summary
   The chapter starts with Lennie arriving upon the hiding spot that he and George talked about. After Lennie talks to himself about George, he hallucinates his Aunt Clara scolding him that he is always causing George trouble. Lennie then hallucinates a giant rabbit telling him that George will leave him. George then finds Lennie and tells him that he won't leave. After a while of talking, Lennie once again asks George to tell the story about the dream farm. George asks Lennie to turn towards the river and starts describing it. Then, out of his pocket, George takes out Carlson's Luger (meaning that the one who stole it in the first place was George) and, at first, he can't bring himself to shoot Lennie. However, after the voices from the others approach them, George decides to finally end Lennie's life by shooting him in the back of the neck. Slim, Curley, and Carlson arrive at the scene to see Lennie dead and George holding the shotgun. George affirms that Lennie had the shotgun. After a heavy-hearted conversation, George and Slim head up the trail towards town, thus concluding the book.
