* Chapter 53
  Pi realizes that his life is in danger with Richard Parker aboard the boat. Discovering that he has a strong will to live, he thinks of ways to avoid Richard Parker and survive. Quickly, Pi begins crafting a raft out of oars, buoyant rope, and the lifebuoy.
  
  As Pi is crafting the raft, Richard Parker, just a few feet away from Pi, finally kills the hyena. Richard Parker turns his gaze towards Pi.
  
  Suddenly, a rat appears and attaches itself onto Pi's head, further drawing Richard Parker's attention. As Richard Parker slowly encroaches closer on Pi, Pi throws the rat into his mouth as an offering, which satisified the tiger.
  
  As Richard Parker goes back to eat the hyena again, Pi quickly finishes the raft, noting Richard Parker's seasickness. The raft, although small, floats perfectly, but Pi is wary of sharks or waves potentially stranding him.
  
  The day quickly starts to end, and rain begins falling. Pi pulls himself up onto the boat to fetch a rain catcher, a bag, and a blanket. In the process of doing so, he slams the locker, annoying Richard Parker. Pi falls back to the raft.
