* Chapter 92
  Pi, still starving and thirsty, discovers a several square-mile island made fully out of algae, housing trees. Pi is able to eat the sugary algae and the fresh water it produces, giving him the energy to recover.

  Richard Parker, too, ventures onto the island and quickly gets used to it, though he remains somewhat anxious. Richard Parker recovers, to the worry of Pi, who believes that the tiger may grow more confident and less respectful of Pi. Richard Parker returns to the lifeboat each night after Pi.
  
  After Pi grows healthy enough to walk and explore farther, he comes across plains home to thousands of meerkats. The meerkats are friendly, and the plains also feature ponds of freshwater.

  Interestingly, the meerkats swim into the freshwater ponds and return with large fish. Pi surmises that this is due to the saltwater ocean fish dying due to freshwater. Pi also sees Richard Parker in the distance killing an abundance of meerkats. The meerkats are not scared.
  
  Pi cleans the lifeboat and tries to explore the entire island to no avail. Pi, however, does note the change of the algae due to the temperature of the day. In addition, Pi notices that the island holds up well against the elements. This makes him question the lack of other wildlife.
  
  One day after Pi has a dangerous encounter with the reinvigorated Richard Parker, he decides to train Richard Parker again.
  
  As Pi gets more used to the island, he decides to sleep on it, avoiding the lifeboat. Pi makes a makeshift hammock and sleeps in the trees. One day, however, Pi is woken up by the meerkats to see that a striking number of fish and even sharks are deposited in the ponds. After Pi goes back to sleep for a while longer and wakes up, he sees that the dead marine life is no longer there. Pi, not believing this to be the work of the meerkats nor Richard Parker, is puzzled.

  Another day, Pi encounters a tree that seems to have a fruit. After climbing up the tree to acquire it, he realizes that the fruit is not a fruit but rather a ball of leaves. After unwrapping the leaves, he finds a human tooth. Pi finds more of these leaf fruits, each of them containing a tooth. In total, they complete a full set of 32 human teeth.
  
  Pi has his doubts but tries one last experiment in order to confirm them. At night, Pi puts his foot onto the algae and sees that the algae is, in fact, acidic, and the island is, chillingly, carnivorous. This explains the death of the fish and sharks and Richard Parker's reason for returning to the lifeboat every night.
  
  Pi decides that he and Richard Parker need to leave the island. After Richard Parker returns in the night, the anchor rope is dissolved, and the two leave the island.
