* Chapter 61
  This chapter, Pi attempts fishing for food for Richard Parker.
  
  At first, Pi tries using his last leather shoe as bait, but he ends up expending it without catching anything.

  After having a minor internal crisis about his plan to keep Richard Parker alive, Pi looks inside the locker for something to use as bait when he is suddenly hit by a flying fish. Pi tries feeding it to Richard Parker, but the fish flies away. Afterwards, however, a school of flying fish and dorado appears near the boat, some flying over, some landing on the boat itself.

  Both Richard Parker and Pi caught a few flying fish.
  
  Pi rushes back to the raft to prepare the fish but cannot bring himself to kill them with the hatchet. Instead, Pi breaks their necks. Pi is distraught with what he has brought himself to do.
  
  Using the fish's head as bait, Pi manages to catch a dorado, which is much larger. This time, Pi happily hacks away at it with his hatchet, somewhat realizing that he is used to killing now.

  The chapter ends with Pi feeding the dorado to Richard Parker and going to sleep, planning to fish more.
