** Economic Integration
   
   - Globalization pushes for the integration (reduction of trade barriers between countries) of economies. This has benefited economies of developing nations.
   - This also has motivated countries to join trading blocs like the EU, Southern African Development Community, and others.
   - Global exports have increased.
   - Integration also causes concerns over national identity, heritage, and integration has not benefited everyone.
   - Some countries have placed restrictions on immigration because of rapid integration.
   - G-6 countries are the US, Japan, Germany, the UK, France, and Italy.
   - BRIC countries are Brazil, Russia, India, and China.
   - By 2025, the BRIC countries could reach or even overtake the G-6 countries with their high population and resources.
   - The BRIC countries also might eventually slow down, just like the developed G-6 countries.
   - Some BRIC citizens do not receive benefits from integration.
   - Russia and the others may be at risk. Russia's economy is greatly based on crude oil.
   - Globalization has not completely gotten rid of poverty, and disparities exist.
   - These great disparities can cause social instability.
   - The middle class is expanding, which could cause a movement to end these disparities.
