** Governance
   
   - Companies should not just provide goods and services but also serve the public good.
   - Companies would only do this if it were profitable, but the financial crisis may cause them to reconsider.
   - Civil society organizations (CSOs) and nongovernmental organizations (NGOs) aid in providing governance and services.
   - NGOs play a bigger role in developing countries where the government has failed to meet their needs. This makes people turn to NGOs.
   - Corruption is a major issue pushing back humanitarian progress that affects both the developing and developed world.
   - National, state, and international governing bodies are no longer the central, only sources of governance.
   - The UN and NATO need to adapt to keep up with the problems of countries, or they could fall.
   - Private companies, CSOs, and NGOs have emerged to be major forces in worldwide problems.
   - Humanity needs an integrated, collaborative government.
   - Leaders need to think in the longer term, apply knowledge, and work together to save the planet.
