** Humans in the Universe

  *Time Period*: 13 Billion - 200,000 years ago
  
*** Overview

   This Big Era details the creation of the universe and the various events that occurred leading up to the evolution of our human species, the Homo sapiens.
   
   This section will help to tackle three important questions:
   
   - What were the origins of our ancestors?
   - Where do we stand in the universe?
   - What is our significance?
     
*** Why?

   /Why should we learn about the creation of us and our universe?/
   
   Our knowledge of our creation and history changes how we perceive us and our own history. Stories of creation also form the basis of many religions and cultural values, important influences on the lives of many people all throughout time.
   
*** Creation in Religion

   One popular example of a creation myth in religion is the one found in the Bible.

   The Bible states that God creates the universe in seven days, starting with light and dark, the environment and Earth itself, then plants and animals, and finally humans.

   This is not entirely unlike the reasoning that modern science gives today. Earth was created first, with living organisms following suit, although the time tables are slightly scaled.

*** The Early Universe

   Scientists theorize that the universe started with an event called the Big Bang around 13.7 billion years ago. Nothing is known about what, if anything, existed before this.
   
   The Big Bang is characterized by a sudden burst and materializing of energy and matter. The universe expanded at a rate faster than the speed of light but shortly slowed to the speed of expansion nowadays. At this stage, the universe was a hot mass of pure energy and subatomic particles.
   
   Eventually, the universe cooled enough for protons and electrons to come together to form hydrogen and helium. Over time, large clouds of these gases would accumulate and fold in on themselves due to gravity. This caused the formation of stars. More stars accumulated and formed galaxies.

   As stars grew bigger, they created new elements through fission and fusion. Once these stars died out, they introduced these new elements into the universe.
   
   *Note*: All complex matter in the universe was formed at one point from stardust. This is but one reason why planets and life form near stars.
   
*** The Solar System

   Around 4.5 billion years ago, in a specific point far from the center of the Milky Way galaxy, gases and heavy metals collected to form the solar system. While the sun took up most of the matter, small parts clumped together at certain distances due to gravity. These caused the formation of our planets. The heavy metals sunk to create the cores of planets, while the lighter elements formed the crust. The gases contributed to the atmosphere.
   
*** Formation of the Earth

   The Earth started as a hot ball of mass, constantly being hit with asteroids and other space material. After four billion years, however, the Earth cooled down, and the water vapor (thought to come from the asteroids) condensed and formed oceans.
   
   As the Earth cooled, different layers of the planet were formed: the core, mantle, and crust. Along with these came the formation of tectonic plates, which contributed to the ever-changing surface of the Earth.

   These tectonic plates are responsible for the formation of mountains, volcanoes, islands, and various features of the Earth, majorly influencing the people and cultures that would soon come.
   
*** Early Life on Earth

   Not much is concretely known about the first origins of life, but it most probably started with underwater volcanoes forming complex chemicals and creating a "primordial soup" in which life could be born out of. The first organisms were single-celled and evolved gradually.
   
   Some populations of cells evolved the ability to produce energy from the sun through photosynthesis. This had the side effect of producing oxygen. This oxygen slowly built up, transforming the Earth's atmosphere.
   
   Other, more complicated cells called eukaryotic cells also formed. Eventually multi-cellular organisms also came into being. Gradually, plants, animals, and other organisms found their way onto land.
   
*** Human Ancestors

   After the extinction of the dinosaurs, a certain group of species called mammals flourished. In particular, one group, the tree-residing primates, was quite well off. Primates had better vision and comparatively large brains. Hominins, our ancestors, were a part of the primates and could stand up.
   
   *Note*: Hominins appeared in Africa. This means that all humans originate at some point from Africa.
   
   Other hominin species such as the /Homo erectus/ and Neanderthals branched off to other parts of the world.
   
   *Question*: Why did our ancestors appear in Africa first and not elsewhere? Other primates were able to survive the climate of other parts of the world, so that was likely not the determining factor. At this point, farming had not been invented yet either. Was there simply an abundance of resources? Were there less predators?
   
   Hominins were intelligent creatures, having social hierarchies, being able to use tools, and utilizing fire.
   
*** Differences with Humans

   Hominins changed very little in the two million years that they were around. In this time, they did not develop religions, villages, or art.
   
   /So, what makes us different that allowed us to do all of these things?/ This is the primary question that Big Era 2 answers.
   
   *Prediction*: Cooperation and collaboration are key in realizing many of the previously listed achievements. At the cornerstone of these is *communication*. I believe that the difference that sets apart hominins from Homo sapiens is language, or some form of communication that powers the sharing of ideas more complex than simple actions.

*** Summary

   The universe started with a bang. After a while of cooling and passing of stars, complex matter was formed. Complex matter accumulated in places to form stars and planets, including Earth. Life on Earth started with single-cellular organisms created by chemicals sourced from underwater volcanoes. These organisms evolved and life diversified, leading to plants and animals. Fast-forward millions of years, primates are flourishing and a certain group, called the hominins, is able to migrate, stand up, form complex social hierarchies, and use tools. Despite this, they are not as smart or progressed as humans.
