** Human Beings Almost Everywhere
  
  *Time Period*: 200,000 - 10,000 years ago

*** Differences

   The primary difference between the second Big Era and the first Big Era is the appearance of Homo sapiens, or humans. This era marks the start of human history.
   
   The primary difference between this era and the next one, Big Era 3, is that farming had not been invented yet. This era is classified as the Old Stone Age, or Paleolithic period. The next era is classified as the New Stone Age, or Neolithic (hint: Neo) period.
   
*** Overview

   This era contains without a doubt the larger period of human history.
   
   Much of the evidence and reasoning that supports the assertions about this era come from archaeological evidence and genetic mutations due to a lack of any written items or history.
 
*** Why Archaeology?

   /Why and how would you use archaeology as evidence for historical research?/

   Bones, tools, food, and other items can help scholars uncover the way people lived, their diet, the development of technology, the climate at the time, and countless other details. Along with carbon dating, a timeline of information can be developed. This can give us a rather accurate look into the life of the early humans.
   
*** Why DNA?
   
   /How can the analysis of DNA aid in historical research?/
   
   By taking genetic sequences of modern humans and comparing them to each other, we can pick out shared and unique mutations that can tell us more about the history of early humans. People coming from the same ancestors will share most of the same mutations. If a population was isolated from that group of people, modern-day descendants will not share those mutations. This gives us a way to see when groups separated from each other and perhaps where they migrated to.
   
*** Art and Language
   
   Art, found in caves and other surfaces, is the most accurate indicator of how early humans perceived the world. Art gives historians a better look into possible religions or other more abstract, complex ideas that they were trying to convey. Art also partially implies the existence of language.
   
   Language and complex communication as a whole is the crowning achievement of the Homo sapien race that distinguishes it from all other animals. Humans are able to communicate abstract concepts and emotions. This allowed for the accumulation of knowledge in communities, called "collective learning."
   
*** Technology
   
   With the development of language and sharing of ideas, the rate of advancement of technology began to increase. Tools became more specialized, intricate, and varied.
   
*** Migration
   
   As technology evolved, many groups migrated eastward, and the population of Homo sapiens became more interspersed.
   
   It is thought that humans first left Africa and traveled somehow, perhaps by land or through the Arabian Sea by boat, to India. From there, the early explorers ventured further to the east, reaching Southeast Asia and China. A benefit of the journey to Eurasia was that the constant tropical climate would allow for much more abundant resources and progress.

   *Question*: What motivated the early humans to travel across such distances? Was it intentional? Was there overcrowding or a scarcity of resources?
   
   Some groups made their way to Australia and New Zealand by a connecting piece of land. Others ventured to Russia and even Siberia. The harsh environment in those areas warranted the creation of new technology and shift to different diets and hunting techniques.
   
   Through another connecting landmass, some humans reached North America, spreading from Canada to South America.

*** Environmental Impact
   
   Humans quickly found hunting quite easy in their new found environments with animals not used to them. This caused them to over-hunt, leading to the extinction of many popular species, including the mammoth. Humans also burned plants, contributing to new plant growth.
   
   Surprisingly, the takeover of humans also led to the extinction of their relatives, the Neanderthals and hominins, who did not have the complex communication and technology of the humans.
   
   Humans now inhabited the globe. Although the population grew into the millions, the relative size of groups remained the same, only the number of groups having increased.
   
*** Early Society
   
   Not much is known about the specific details of how society and culture worked in the age before writing. We can however gain some vague clues from modern hunting-and-gathering societies.
   
   In these communities, meat is valuable, and hunters and gathers are both knowledgeable. These groups are nomadic and travel as families. Social roles are based on age and gender, and no one accumulates wealth because there is no reason for it.
   
   Nearing the end of the era, communities began to settle down. In order to secure food, they started to take care of the local plant life. This would lead to farming later on.
   
*** Art
   
   Forager communities often painted depictions of animals and nature with some sorts of spirits. As well, jewelry and colorful shells were at the center of artistic expression at the time. Figurines were created by people living in regions without caves. Music was also developed with several woodwind instruments.
   
   Unfortunately, it is hard to determine the true meaning of such objects without context, so multiple viewpoints may apply.

   Despite these many art forms, no sort of written language was developed.
   
*** Summary

   Homo sapiens, or humans, emerge from the hominins and have better brains capable of complex thoughts and communication between each other. Technology rapidly develops and the humans migrate, conquering the globe. While taking over the globe, they have massive impacts on their environments. All the while, an artistic explosion is happening with paintings, jewelry, and music developing. As people begin to settle down at the end of the era, techniques similar to farming start to develop. A written language still has not been created.
