** Farming and the Emergence of Complex Societies
  
  *Time Period*: 10,000 - 1000 BCE
  
*** Overview
   
   In this era, we see the steep rise of the invention of farming and the effect it has on the environment and societies. Farming and the drastic social changes it brought distinguish this Big Era from the previous two.
   
   This era is called the neolithic era, or New Stone Age, due to the innovation and invention of new stone tools, particularly those related to farming.
   
*** Farming
   
   The actual developing of farming was a relatively slow process and did not appear everywhere in the world at the same time. Compared to the timeline of previous human events, however, farming spread quite quickly

   Historians define farming as activities that increase the production of useful items, such as cattle and crops, and the reduction of useless items, like pests and weeds. Farming is not limited to just food. By farming, humans change their environment to suit their needs. This developed agrarian societies, in which communities revolve around agriculture.
   
   Farming used a process called domestication, in which humans selectively breed plants to change them to their benefit. As plants were further domesticated, they became co-dependent, unable to produce without human intervention. This also had the slightly unfortunate side effect of preventing a society from returning to foraging in that area.

*** Population Change
   
   As opposed to extensification (the increasing of communities) seen in the previous chapter, this era, in large part due to farming and communities settling down, sees intensification (the increasing of the populations of communities). This caused the population to sky-rocket into the hundred millions, also causing social changes in communities.
   
*** Climate Change
   
   In this era, the globe gradually started to warm up. This led to the shrinking of glaciers and rising of sea levels. This had two major effects.
   
   1. Land bridges connecting Afroeurasia, the Americas, and Australia disappeared underwater, disconnecting travel.
   2. Parts of the Northern Hemisphere warmed up and became much more bountiful, particularly the Fertile Crescent, an area in the Middle East.
      
*** Social Change
   
   Particularly in places such as the near Tigris River, Euphrates River, Nile River, the Indus Valley, and Huang River, populations flourished and communities evolved to be more complex cities and civilizations.
   
   Cities did suffer consequences, however. Cities were particularly vulnerable to change in their environment, disease and socioeconomic and political problems.

   In the beginning of the era, most people were still on equal status. Everyone farmed, and while there were leaders, they did not have power over people.
   
   After a few thousand years, however, complex societies formed. This led to a wide variety of advancements

   - Cities formed.
   - Jobs became more varied and specialized.
   - Social hierarchies and patriarchy developed.
   - A centralized government was formed.
   - Trades took place.
   - Technology advanced.
   - Architecture was built.
   - A writing or record system was made.
   - Religion, laws, and art progressed.
   - Sciences and mathematics were worked on.

   In places were agricultural was not viable, such as the Sahara Desert, the system of pastoral nomadism was implemented. These were societies based on herding domesticated cattle, living off of their products while migrating.
   
   These two types of societies interacted, sometimes peacefully and sometimes violently. The migrational tendencies of the pastoral nomadic tribes also helped them foster trade between cities.
   
*** Change in Ideas
   
   With the condensing of populations, information and ideas were spread at a faster rate and in more abundance. Religious knowledge, technology, and writing were spread quite quickly.

   One civilization in particular, the Sumerians of Mesopotamia, made countless breakthroughs in various areas.
   
   - A system of writing, cuneiform, was developed.
   - Mathematics in base-10 and base-60 was developed.
   - Government, commerce, astronomy, and architecture improved.
   - Concepts such as bronze metallurgy and the wheel were invented.
     
   Each civilization had their own dynamic cultural styles.
   
*** Summary
   
   The newest invention on the block has, albeit gradually, come: agriculture. The domestication of plants and animals to the needs of humans coupled with global warming allows people to settle down and populations of communities themselves to grow. This leads to complex communities and civilizations forming, containing governments and even social classes. These complex communities lead to more ideas, technology, and innovation, including the appearance of an early writing system.
