** Expanding Networks of Exchange and Encounter
  
  *Time Period*: 1200 BCE - 500 CE
  
*** Overview
   
   This Big Era is all about the increasing of networks and communication between the newly formed cities and states from Big Era 3. In this Big Era, roads and sea networks emerge, connecting large parts of the world together and transmitting goods, technology, and ideas (particularly religion).
   
*** Environment
   
   In this period, novel changes in the environment were not seen; however, agriculture and its impact on the environment did increase.
   
   One example of this is deforestation. People needed more area for farming and living, leading to mass deforestation in some parts of the world. This had quite a few consequences. Wood shortages, famines, and the potential extinction of species were all shortcomings of the mass clearing of land. This might have even contributed to the changing of the planet's climate.
   
*** Technology
   
   Techniques such as breeding hybrid crops and using horses and camels for work began to appear. In addition, this era saw the emergence of iron metallurgy. With the increase of networking, technologies such as these rapidly spread across the world. Despite this, some areas that were not as connected, such as the Americas and Oceania, were not as quick to pick up on them.
   
*** Populations
   
   Population and its rate of growth continued to rise. This was due to agriculture as well as built up immunities to common diseases. Because of the crowded nature of cities, these immunities were built up naturally and allowed for more population growth.

   Once again, this population growth warranted a restructuring of the layout of societies, causing many to move towards cities. Despite this, though, the amount of cities declined at the end of the era, likely due to pandemics and the declining of empires.
   
   Two particularly important, large cities were Rome and Luoyang. These cities, like others, served as centers for government, trade, art, and religion among other things.

*** Empires
   
   With faster ways of transmitting information (horses, roads, etc.), leaders could exert more power over larger areas of land. This aided in the rise of empires. The three main empires at the time were the Han empire, the Persian empire, and the Roman empire. *These states were named empires because one governmental body exercised control over different, diverse groups of people.*
   
   From around 100 CE onward, several empires, almost spanning the entire length of Eurasia, prospered. This led them to exchange products and ideas between each other. This led to increased trade activity on the silk roads.

*** Society
   
   Inside the cities, novel social changes took place. Social classes became more varied and based off of wealth and power. There was also an increase in the usage of slaves. Finally, societies moved further towards patriarchy.
   
*** Language
   
   One important distinction between this Big Era and the previous one is the development of new writing systems. These writing systems used alphabets instead of logographic characters. This allowed for an increased literacy rate. Some logographic systems still remained, however.
   
*** Religion
   
   As a consequence of an easier way of writing and a more efficient way of transmitting this writing, major religions developed. Six major religions at the time were:
   
   1. Buddhism
   2. Christianity
   3. Confucianism
   4. Daoism
   5. Hinduism
   6. Judaism
      
   With the exception of Islam, these make up the modern major religions. These all likely were formed due to the need of a moral system at a bigger scale. These religions all have their own characteristics and ways of answering existential questions about human life. Some of them, particularly Christianity, had different branches and variations.
   
   Particularly in Greece, philosophy emerged, with scholars trying to find reason and patterns in nature.
   
*** Summary
   
   Following the big boom of agriculture, the population keeps growing and cities follow suit. Communication and interaction between these cities and states develop and becomes critical for the exchanging of goods, technology, religion, and ideas. With this efficient communication comes empires, now annexing more land than ever and reaching people of varying ethnicities. The alphabet develops, leading to higher literacy. Finally, major religions and moral systems are formed with the spread of ideas.
