** Patterns of Interregional Unity
  
  *Time Period*: 300 - 1500 CE
  
*** Overview
   
   This Big Era marks the end of the ancient world and the emergence of some modern world traits. In this period, the growth rate again climbed, more empires and states were formed, trade (especially in the Indian Ocean) skyrocketed, and major religions further developed.
   
*** Population

   At the beginning of the era, the population actually declined for around three centuries, likely due to drier conditions, epidemics, and economic recession.
   
   After a while, the growth rate climbed back and continued for seven centuries. Nearing the end of the era, another recession occurred after several epidemics, including the Black Death, hit Eurasia. By the end of the era, the population again recovered and reached around 400 million.

*** Agriculture
   
   One major reason for the increase of population at the end of the era was the improved agricultural technology. Technology enabled more land to be made into farmland and increased the output per area of land.
   
*** Trade
   
   New technology allowed groups to move at a faster pace on both land and water. This not only empowered empires militarily, but also greatly promoted trade. In particular, new vessels and navigational tools allowed for water to serve as another route for trade, with the Indian Ocean being the most active. This is also another reason for the growth of the population.
   
   Towards the middle of the era, trade and commerce picked up in Afroeurasia. In particular, China, India, and Islamic states became wealthy through manufacturing goods and trading them. This wide network of trade soon got nearly the entire eastern hemisphere involved.
   
*** Environment
   
   The environment takes a pretty heavy hit in this Big Era. With the demand for wood and urbanization increasing, deforestation rates also increased. As a consequence, soil degraded, floods became more common, famines occurred, and wood became more scarce.
   
*** Empires
   
   With new technology, pastoral nomads posed a big threat to many established empires. Invasions from the Uighurs, Huns, Arabs, and others contributed to the fall of the Roman empire.
   
   New empires were built, such as the Gupta empire of India, Arab empire of the west Afroeurasia, and Tang and Sung empires of China. After Mongol invasions, however, these empires too collapsed. The Mongols took over their land and built the largest empire in history, spanning 7 million miles.
   
   In Europe, the Byzantine and Russian empires appeared. In Africa, the states of Ghana and Mali formed. In Asia, the Srivijaya and Majapahit empires formed. Several other empires formed in the Americas.
   
*** Technology
   
   With new technology in the form of catapults, bows, and even gunpowder muskets, warfare became more bloody and complex.
   
   In terms of weapons, naval warfare did not change much, but navigation and the distance ships could travel did improve. This also allowed for Christopher Columbus in the late 15th century to discover the Americas.
   
   Land and sea trade routes allowed for the exchange of new inventions, technology, and ideas. This Big Era saw advancements in mathematics, language, astronomy, and education itself. The abacus, paper, and the printing press were developed and subsequently spread via trade routes. In Muslim and Christian society, predecessors to universities were formed as places were intellectuals could gather. The idea of a college was also introduced and spread throughout Europe.
   
*** Religion
   
   This Big Era saw the emergence and spread of major belief systems. Religions such as Hellenism (originating in Greece and focusing on reasoning), Judaism, Christianity (split between the Roman pope and the Eastern Orthodoxy), Hinduism, Buddhism, Daoism, and Confucianism all spread through various places in Afroeurasia.
   
   One major happening in this Big Era was the formation of the religion Islam, one of the three universalist religions. Islam is a monotheistic and missionary religion, having a scripture, the Qur'an, and the Prophet Muhammad. Due to conquests and conversion, Islam quickly spread and gained large ground, stretching from Spain to India and including large parts of Northern Africa.
   
   It is important to note that religion was more prevalent and strong near large cities. In more rural areas, local religions were practiced, most involving nature.
   
   In the west hemisphere, indigenous religions consolidated. With the exception of the Mayans, Aztecs, and Incas, local religions were much more common.

*** Summary
   
   With trade routes and new navigational technology, the world became more connected than ever. Technological innovations and political changes allowed for a greater population, in spite of several epidemics. Major religions developed and spread, with Islam emerging. Although there was mass deforestation and environmental damages, humanity managed to progress at a rate faster than anything before.
