** The Great Global Convergence
  
  *Time Period*: 1400 - 1800 CE

*** Overview
   
   In this Big Era, the connections between individuals and societies further develops. The most defining event that happened in this era was the connecting of every inhabited region of the world to each other, called "The Great Global Convergence." Five major changes distinguish this era.
   
   1. Human connections become more complex, notably with the new interaction between Afroeurasia and the Americas.
   2. The Columbian Exchange occurred, involving the transport of plants, animals, and bacteria between the Americas and Afroeurasia. Diseases brought along caused the deaths of many indigenous people, and Europeans brought back home new crops.
   3. A fully global economy was formed with the currency being silver.
   4. Europe rose in military and political power.
   5. Western Europe underwent the Scientific Revolution and the Enlightenment, which challenged several religions and philosophies.
      
*** Humans and the Environment
**** Population Changes

   The population grew even faster in Afroeurasia during this period. Conversely, the population plummeted in the Americas, called the Great Dying. What did remain the same was that only a few percent of people stayed in cities or were foragers; most people, 95%, continued to lived as farmers.

**** The Great Dying
   
   After the Spanish arrived in the Americas, they accidentally brought along with them microorganisms and bacteria. The indigenous people had no immunities to these microorganisms, and this led to outbreaks and pandemics that ravaged the population.
   
   This affected both the indigenous and Spanish people. The outbreak brought about the fall of the Aztec and Inca empires. In addition, decreased populations of Native Americans also resulted in labor shortages for the Spanish.
   
   The Spanish also brought along domesticated animals and plants. Because the climate was similar to Europe's and the existing wildlife had not adapted to them, the new wildlife quickly took over and transformed the environment of North America.
   
**** The African Slave Trade

   With the need for new labor in the Americas, especially for farming, Europeans brought in African slaves in large numbers. The slaves proved to be a profitable solution for the new settlers. Around 11 million able African workers were taken from their homes.
   
   Although they still remained in the minority in terms of population, around 2 million Europeans migrated to the Americas.
   
**** Rampant Deforestation
   
   Due to higher demands for wood as well as the expansion of mining, deforestation plagued large parts of the world.
   
   In response, Europe moved towards other solutions, eventually settling on fossil fuels. Japan, in contrast, worked towards reforestation.
   
*** Humans and Other Humans
**** A Shift in the Economic Center of Gravity
    
    Although Asia was at the center of trade and commerce during the start of this Big Era, Europe quickly closed the gap with the precious metals and sugar they were able to obtain in the Americas. This benefited both sides.

**** Revolution in Military Power and Finance
    
    Europe also rose in power due to innovations in gunpowder weaponry, strategy, tactics, and other elements. Europe fought multiple battles during this period, allowing them to innovate in warfare technology.
    
    Not every country was equal, however. Especially in North America and South Asia, Britain prevailed over France.
    
    Finance and economy had to be reconsidered by many countries in order to fund the large amounts of weaponry. Britain ultimately won over France due to France's lesser funding, part of which went to the American Revolution.
    
    Although the power was shifting to Europe, most countries were still not able to take on countries in Asia and Africa that were also armed.
    
*** Humans and Ideas
**** Cultural Developments in Europe
    
    Following the long period of plagues, Europe revived itself with the Renaissance, a cultural expression of new wealth. The Renaissance by itself, however, was not a true, major cultural change. Much more changing was the Scientific Revolution of the 17th century.
    
    One invention, the printing press, was invented in the 15th century and allowed ideas to be spread much faster. This had major implications on cultural and religious developments. An example of this is the Protestant Revolution, led by Martin Luther and causing multiple branches to form from the original Roman Catholic Church.
    
**** The Global Religious Scene
    
    Christianity and Islam quickly spread through the Americas and Afroeurasia respectively. Despite these developments, no religion held a monopoly on the world, and most followers were not very strict or knowledgeable.
    
**** The Scientific Revolution
    
    With Christianity being challenged with the Protestant Revolution, discovery of the Americas, and knowledge from other parts of the world, many scholars saw the chance to develop reasoning and science to question the old way of thinking. These scholars argued that the world was not entirely governed by religion, but it worked based on natural laws.
    
    This would lead to further developments in the Enlightenment in the 18th century.

*** Summary
   
   Western Europe pioneered a conquest to travel west and discovered the Americas, forever changing the history of the planet. The Europeans quickly took over large spans of land and extracted resources such as precious metals and sugar, at the expense of African slaves and the lives of many indigenous people. This, coupled with wars, allowed Europe to gain a more powerful economic and militaristic standing in the world. Back in Europe, the Renaissance and Protestant Revolution shook the continent, challenging the authority of the Church. Reasoning and scientific thought developed during the Scientific Revolution, which also questioned the Church's prevalence over society.
