** Industrialization and its Consequences
  
  *Time Period*: 1750 - 1914 CE
  
*** Overview
   
   This Big Era was an important era for history and is often called the era of the "modern revolution." The events of this era are termed "autocatalytic" because changes that occurred in this era caused other changes to happen, leading to exponential growth and accelerating change.

   This Big Era featured six major related developments.

   1. Humans now moved on to use fossil fuels and steam for power.
   2. Massive population growth happened, with the population reaching more than one billion people by the end of the era.
   3. The Industrial Revolution occurred.
   4. Transport and communication advanced.
   5. A movement for democracy emerged.
   6. Empires gained power.
   
*** Humans and the Environment
**** Fossil Fuels
    
    Fossil fuels such as coal, oil, and natural gas allowed for greater energy output at a lower cost. These factors led to coal providing 90% of all energy for humans by the end of the era.
    
**** Many More People
    
    By the end of Big Era 7, the world population had an increase of 200%, with 1.79 billion people on the planet. This, combined with fossil fuels, greatly influenced the environment.

    The population quickly grew in western Europe, the same thing later happening in Asia and Latin America.
    
    Due to epidemics, the indigenous population declined.
    
    With more people, urbanization increased and cities grew bigger. A much larger population lived in cities compared to earlier Big Eras.
    
**** Mass Migrations
    
    With steamships and railroads, large volume migrations became much more reasonable. Around 50 million people from Europe migrated to places in the Americas and Australia. These settlers pushed out indigenous people and exploited the resources of the land.
    
    1.7 million Africans were forcefully migrated to the Americas to work as slaves.
    
    In Asia, around 30-40 million Indians and 15 million Chinese migrated to find work in mines and plantations in Europe, the Americas, and Africa. Some stayed, while others left due to poor treatment.
    
    Internal migrations were also common in countries.
    
**** Environmental Impact of Industrialization and Migration
    
    With new technology, humans had more power to change the environment. Deforestation and pollution increased. Plants and animals from parts the world were transported to environments that had not adapted to them. This led to the spread of invasive species.
    
    In addition, multiple significant famines took place, caused by a shortage of food and ignorance from country leaders. These famines showed the gap in living standards between developed and developing countries.
    
*** Humans and Other Humans
**** The Emergence of Liberalism
    
    Along with the modern revolution came the ideas of liberalism, which favored individual rights, free markets, republican governments, and change. Liberalists called for private property, better communications and transport, modern markets, democracy, and separation of church and state.
    
**** Economic Trends
    
    With coal and steam power, production increased. The invention of railroads allowed for the faster transport of humans and goods.
    
    These progressions allowed for a change in the world economy. Rural countries adapted to export raw materials and import finished goods from more industrial countries. An example of this is cotton, which overtook sugar as the most important commercial crop and become an important import for Britain, which exported cotton textiles.
    
    Sometimes, European countries went against the belief of a free market. An example of this is the Opium War between Great Britain and China. Britain fought a war to force China to open trade for Britain's opium. This strained the Chinese economy and led to an outbreak opium addictions. Several other countries including the United States used this policy in trading with Asian, Middle Eastern, and Latin American countries.
    
    Gold was standardized following the discovery of it in various countries.
    
    The end of this Big Era saw another explosion of growth, with new technology such as the telephone and the semi-automation of agriculture.
    
    Following liberalism, companies, holding private capital and property, grew in power.
    
    The downside of the inclusion of a global economy was that it potentially made individual economies weaker.
    
**** Political Trends
    
    At the start of the Big Era, Britain acted as the top global power.
    
    Around the world, several revolutions occurred with the ideals of liberalism at heart. The Thirteen Colonies of America was the first revolution, followed by the French Revolution, Haitian Revolution, and other revolutions in Latin America. These revolutions replaced their governments with republics. Voting rights were given to adult males who held property. At first, slavery was not dealt with, but anti-slavery movements appeared later on.
    
    Another major change was the abolishment of slavery. Although Britain and America abolished the slave trade, it was not until near the end of the Big Era that slavery was completely eliminated. Despite the defeat of slavery, other forms of involuntary work existed.
    
**** Colonial Encounters
    
    The gap between the rich and poor was drastically widened with the expansion of European colonies.
    
    There was resistance to take over from many local residents, but they could not win against the advanced weaponry of the Europeans. At the end of the era, European countries controlled most of the world.

*** Humans and Ideas
**** The Rise of Secularism
    
    Following the liberalist idea of progress and change, people used science as a way to challenge traditionalist religions. The secular, or worldly, side argued that events did not necessarily occur with purpose and that the world was not created supernaturally. These ideals spread throughout Europe and sparked much debate between both sides.
    
**** 19th Century Racism
    
    Many people construed Charles Darwin's theory of "survival of the fittest" to justify racism and colonization.
    
**** Thriving Religions
    
    Even with secularism and science challenging religion, faith spread and grew at a faster rate. Religious scriptures could be written and sent across the globe. In particular, Christian missionaries were sent all around the world in order to spread their faith.
    
    Religion, being more traditional, was opposed to fast change, liberalism, and colonialism. Despite these beliefs, none could challenge the weaponry and power of the European countries.
    
    As liberalism spread throughout the world, many debated economic reforms. In the end, they were not popular with the elites or those who suffered from change.
    
    The viewpoints on both slavery, popular sovereignty, and workers' rights changed drastically, but positively, from the start to the end of the era.
    
    Another major change founded in this Big Era was the development of the idea of nationalism, which led to these major revolutions. 
    
*** Summary
   
   This Big Era is deemed the era of "modern revolution," with the large changes it brought. Industrialization, with fossil fuels and steam at the center, greatly advanced the world's technology and led to even more population growth as well as massive changes to global economy. Along with industrialization came colonialism and liberalism. With colonialism, many countries in Europe began conquests and took over land across the globe to create colonies. Liberalism, on the other hand, pushed for the creation of republics, called for fast change, encouraged revolts, challenged religion, and completely changed society and politics.
