** A Half Century of Crisis
  
  *Time Period*: 1900 - 1950 CE
  
*** Overview
   
   As Europe industrialized, it slowly began to take over and influence the world. Countries that were not industrialized often lost economic standing in the world, unable to keep up with automation and technology of other countries.
   
   Increased competition and rapid change led to six major happenings that changed the world as a whole:
   
   - The natural environment was strained to due fast growth.
   - Costly tariffs harmed equal global economics.
   - Two world wars greatly harmed European and certain Asian countries, both economically and physically.
   - Countries with rising economies challenged Europe's monopoly of the world.
   - Nationalism and colonialism lost influence and weakened.
   - New world events caused the re-evaluation of liberalism and elitism.

     By the end of era, two superpowers emerged, the United States and the USSR.
     
*** Humans and the Environment
**** New Technology and Population Growth
    
    Despite wars and conflict, the population continued to grow in all parts of the world. With new technology like fertilizers, food production increased.
    
    Better understanding of medicine and diseases allowed for the creation of vaccines, which greatly increased life expectancies and led to a decline in the death rate.

**** The Shift to Cities
    
    Rapid population growth caused many people to move from rural parts of countries to cities and other countries, causing urbanization. Sanitation in cities led to even lower death rates.
    
**** Humans Reshaping the Environment
    
    Both cities and farmland encroached onto previously untouched land. This led to even more deforestation, particularly in tropical areas. This deforestation and over-farming led to land erosion. One severe consequence of this was the United States dust bowl.
    
    People gradually began to use energy and produce more waste. Coal was used even more and oil was used in combustion engines over steam, polluting the air.
    
    The GDP of the world doubled and production increased greatly. In addition, nuclear energy was also discovered. These factors combined showed that humans were the single most influential force in the environment, signaling the beginning of the Anthropocene era.
    
*** Humans and Other Humans
**** The Economic Roller 
    
    Between 1870 and 1950, the global economy increased, decreased, increased, and decreased again, leaving the economy worse than it was in 1870.

    This happened due to countries becoming protectionist and imposing tariffs. These increased competition in global markets. After the World War I, which settled some of the competition, surplus goods still did not sell well. War costs and German and Austrian reparations complicated finance systems and led to many loans, especially from American bankers.
    
    After Americans bankers pulled their money back, the world economy crashed, causing production and employment to fall. This "Crash of 1929" hit industrialized regions and the regions that depended on them. As governments spent less and raised more tariffs, the situation worsened.
    
    It was only after the government started spending money, stimulating the economy with the New Deal, that the Great Depression started to improve. This led to a higher involvement of government in economies.
    
    The last push that ended the Great Depression was the beginning of World War II.
    
**** The Great War
    
    As countries began making weapons and forming alliances in Europe, tensions rose. After the assassination of Archduke Francis Ferdinand of Austria-Hungry, a chain reaction occurred, starting the first World War.
    
    World War I proved to be violent, killing millions. Back at home, governments were able to gain more power and the lives of citizens were transformed.
    
    After multiple years of fighting, the United States joined the Allied side, which was the last push that ended the war and made Germany surrender.

    The war left tens of millions dead or injured and destroyed economies and infrastructure.
    
    The Treaty of Versailles left Germany and Austria to face harsh reparations. In addition, the first world body, the League of Nations, was formed in order to prevent future wars, but it held little power.
    
**** Soviet Union
    
    Russia saw the creation of the first communist state, which went in direct opposition of the capitalist system. After economic strains because of the war, Tsar Nicholas II abdicated. In his place came the Bolshevik Party, which was headed by Vladimir Lenin, a Marxist who was against liberalism.
    
    Under the Bolsheviks, Russia left the war, won a inner struggle, and got rid of influential capitalists. This transformed Russia into the USSR, which was poorer and less advanced than its earlier counterpart.
    
    The successor of Lenin, Joseph Stalin, industrialized Russia, changed its economy, and took away land from the peasants.
    
    At the cost of famines, labor camps, and the lives of millions, the USSR achieved a powerful economy. This went on to inspire China to become Communist under Mao Zedong.
    
**** Fascist Governments
    
    Germany's Adolf Hitler pioneered Nazism (National Socialism) and advocated for fascism. Hitler quickly rose to power with his Nazi party and became the leader of Germany. As a result, Germany disregarded the Treaty of Versailles and prepared for war and invasion. Fascism was also implemented in Italy by Benito Mussolini.

**** Nationalism in the Colonized World
    
    Inspired by liberalism and nationalism, colonies began to challenge their European rulers.
    
    After losing the war, Germany and Austria lost their colonies to Britain and France. Turkey, on the other hand, became an independent state.
    
    Nationalist movements empowered other vies for independence from countries such as India, countries in Africa, China, and Vietnam.
    
**** Challenges to Democracies
    
    Democracies were pressured to make voting more available to populations such as women, with New Zealand being the first to do this.
    
**** World War II
    
    Tensions and challenges in the 1920s and 1930s eventually bubbled up to start World War II. Japan invaded China, Italy invaded Ethiopia, and Germany invaded Austria, Czechoslovakia, and Poland, which signified the start of the war.

    After allying with the Soviet Union to invade Poland, Germany turned on them. Japan attacked Pearl Harbor, bringing the United States into the war. As a result, World War II was fought on every continent in the world except Antarctica.

    Eventually, the Allies overpowered Germany and Italy, and the US used two nuclear weapons on Japan, which ended the war entirely.
    
    Around 60 million people died, and expenses were even higher. People also saw the true horror of how Jewish people were being treated during the Holocaust.
    
*** Humans and Ideas
**** Science and Art
    
    This era saw scientists and artists such as Albert Einstein, Werner Heisenberg, Sigmund Freud, and Pablo Picasso. New genres of art emerged and motion pictures, radio, and jazz brought a new form of entertainment.
    
**** Mass Communication and Popular Culture
    
    Popular culture spread to the entire world. Movies and radios allowed people to reach far audiences and transmit novel ideas and cultures. Newspapers and sports developed, and luxury and entertainment no longer became exclusive to the upper class.
    
    By the end of Big Era 8, the world was no longer controlled by Europe and no longer fixed on liberalism.
    
    Many wondered whether peace would be achievable after the Industrial Revolution.

*** Summary
   
   As two World Wars break out, major social, political, and economic changes occur. Liberalism and rapid change is no longer seen as a goal by many, but nationalism continues to be a driving factor that challenges colonialism. The political concepts of communism and fascism emerge, with Russia and China being the main proponents of communism.
   

