** Paradoxes of Global Acceleration
  
  *Time Period*: 1945 - Present
  
*** Overview
   
   One unique point about this Big Era is that it is still underway. Many things are still unknown, but there are some trends and a few important events.
   
   - The human population has almost reached 8 billion people. With many living in cities.
   - Environmental harm and strain has became even more prevalent and worse than ever.
   - Humans have developed better technology to extract energy.
   - The Cold War occurred, the United States became the leading global power, and the United Nations was formed.
   - Modern technology like the internet and mobile phones allowed for even greater connection with people all over the world.
   - Weaponry and country management became expensive, leading to the straining of the economies of many states. In addition, terrorist groups have arisen.
     
   This era is described as paradoxical, with many people experiencing both extremes of wealth, living conditions, and opportunities.
   
*** Humans and the Environment
**** Population Growth and its Environmental Effects
    
    Average life expectancies rose from 35 to 55 years old, causing an increase in population. This was due to new medicines, sanitation, and healthcare.
    
    Agriculture also developed with irrigation, fertilizers, pesticides, and GMOs. This did, however, weaken the food chain.
    
    Population growth caused an even greater impact on nature than before, with many animals going nearly extinct.
    
**** Colossal Energy Consumption and the Environment
    
    Worldwide energy consumption increased by 400%, and reliance of fossil fuels went up.
    
    Large clearings of land were made for automobiles, and more efficient travel also meant more efficient disease spread. Many chemicals, such as the ozone-layer-destroying CFCs, were created.
    
    The use of fossil fuels put large amounts of $CO_2$ into the atmosphere, which contributed to global warming and other drastic, harmful forms of climate change. Nuclear power also proved to be somewhat dangerous due to the radioactive nuclear waste.
    
    Some nations have started plans to repair the environment and stop diseases, but not all nations were able to.
    
    Birth rates slowed down in more urban regions.
    
*** Humans and Other Humans
**** Big Science
    
    Governments became more involved in research and development. This led to the discovery of DNA and inventions in biotechnology.
    
**** Global Migration
    
    Cheaper travel and relaxed movement restrictions led to millions of migrants. Many moved to North America and Australia, and others moved to bordering countries.
    
**** Electronic Communication
    
    Phones and computers quickly became common household items. This allowed for the world to become globally connected and share culture in a much more efficient way.
    
**** Postwar Economic Growth and Trade
    
    After the war, the Allies invested money into reviving the world economy and trade, which contributed to the GDP growing immensely. More workers also appeared, further helping the progress.
    
    In wealthier nations, living standards increased, widening the gap with developing countries. As developing parts of the world accrued debts, the global growth slowed.
    
**** The Cold War and its End
    
    The Cold War was a period of raised tensions between countries holding two different economic ideologies, capitalism and communism. The Cold War also resulted in many colonies achieving independence.
    
    After the Cold War, the Soviet Union broke into several states, returning the world economy to following mostly capitalist ideals.
    
    The eastern hemisphere gradually grew as well, with the formation of the European Union and Russian Federation.
    
**** Sovereignty and Rights
    
    One major development of this era was nationalism-powered anti-colonialism.
    
    This big era also saw the standardization of global human rights with from the UN. Because of this, more attention was brought to children's rights and forced labor other than slavery.
    
**** The Passing of Peasantries
    
    In most parts of the world, less and less people worked as peasants on land. More than half the population lived and worked in cities.
    
**** Women's Rights
    
    Following the formation of the UN, a multitude of conferences have been held for women's rights and the elimination of discrimination. In the majority of countries in the world, women hold rights equal to men.
    
*** Humans and Ideas
**** Environmental Consciousness
    
    As more data has been gathered, and more people become aware, more attention has been focused towards combating global warming and taking care of the environment.
    
**** Global Culture
    
    Different cultures have spread all around the world. Food, clothing, music, and other elements became shared at a global level.
    
**** Marxism and Neo-Liberalism
    
    Two more modern belief systems, Marxism and neo-Liberalism, emerge; however, both have proven to be unpopular.
    
**** Religion and Science
    
    With the globalization of culture, many traditional ideas of religion have been compared and challenged. Religions have adapted to rethink their relationships to other religions, and many local religions have died out. Religious figures and sites have been made much more accessible
    
    In regards to science, massive breakthroughs and research into new fields have emerged. Some, such as biotechnology and genetic engineering, lead to moral dilemmas.
    
    This present Big Era shows radical discovery and advancement, but also leaves many questions moving forward.
    
*** Summary
   
   After the Cold War ended with capitalism rising as the victor, massive changes greatly affected people on a global scale. The population once again boomed, technological and scientific advancements have been made in abundance, and economies have grown and possibly stabilized. A greater concern than ever has been placed on environmental awareness and climate change. The world is now interconnected, and people from all over the world interact. Not much is certain moving forward, but only time will tell.
