* Author's Note
  The author of /Life of Pi/ is Yann Martel. In 1996, he released his second novel, and it was not received well, being quite unpopular. Martel then moved on to writing another novel in 1939, this time set in Portugal. As he did not have much money and was familiar with the region, Martel flew to live in Bombay, where he could live and settle down with less financial worry. Martel, dreaming a peaceful life of writing near a hill-side, began writing his third novel. In spite of the beauty of the characters, plot, and setting, Martel felt some emotional element was missing and was somewhat disheartened, and he ended up mailing away his notes to a fictional address. Martel, with even less money, decided to travel to South India. Martel then arrived at a town called Pondicherry, which was previously under rule by the French empire. At a place called the Indian Coffee House, Martel met a man, _Francis Adirubasamy_, who was curious with his work and told him, "I have a story that will make you believe in God." At first, Martel did not believe him, but he relented and sat down to listen. The man mentioned the botanical garden's toy train tracks and how the train used to run twice an hour every day through the stations Roseville and Zootown. The man asked Martel to talk to the main character (of the book?) for his questions to be answered. When Martel went back to Toronto some time later, he called a certain Mr. Patel, the man Adirubasamy mentioned. The main character recalled his story and showed his diary and newspaper records to Martel. Martel then managed to get a tape from the Japanese Ministry of Transport. What Martel found did make him believe in God. This book, /Life of Pi/, is the main character's story.
