* Chapter 17
  In this chapter, Pi recounts his first interaction with Christianity in his trip to the hill station Munnar.

  When Pi visited Munnar, he noticed three hills, each with their own building. The hill on the right had a Hindu temple. The one in the middle had a mosque, and the one furthest left held a Christian church. Curious about it, Pi went to the left hill to visit the church, arriving at the rectory. There, Pi saw how the doors to the priest and assistant's room were open and remarked at the comforting and welcoming environment. This deepened his interest in the church, causing him to go inside and question what he saw.

  Later, Pi actually went in a talked to Father Martin, who told Pi the story of Christianity. First hearing it, Pi was quite confused about how God's Son paid the price for the sins of humanity. Pi was confused how God could die and why he would lower himself to the human level. It perplexed him more that God would not leave a descendant. When he questioned Father Martin about it, he replied that it was out of love.
  
  All of these questions made Pi interested in the religion, and God would not leave his mind.
  
  On the last day of Pi's stay in Munnar, he went to the church and asked Father Martin if he could be a Christian, to which he responded that Pi already was a Christian in his heart. Pi was delighted and made his way to the Hindu church to thank Krishna for introducing Jesus to him.
