* Chatper 26
  One day, Pi works up the courage to confront his family about the situation.

  Pi asks his father for a baptizing and a prayer rug, wishing to practice Hinduism, Christianity, and Islam at the same time. When asked why he wants to pray, Pi responds that he loves God. His father still does not relent and explains that he does not have to practice three religions, but Pi says that he wants to. When Pi's father says that he cannot follow all three religions at once, Pi disagrees. In a classic father move, Pi's father tells Pi to talk to his mother about it.
  
  Pi confronts his mother with the same request. Pi's mother says to talk to his father about it, but Pi informs her that he already did. Pi's mother then tries to distract Pi with a book to read, but Pi sees through her. Pi's mother explains that they do not understand Pi's enthusiasm for religion and that she does not believe that Pi can follow three religions at once. Pi relates religions to nations and manages to somewhat win the argument with his mother, who relents.
