* Chapter 21
  This chapter is quite cryptic in its meaning. The style again reverts to the italic text, signifying that this involves Richard Parker somehow.

  Pi, presumbably, after having met with Richard Parker, felt down about the contentment of his life, which Parker described with, "'dry, yeastless factuality', 'the better story'" (21.1). Pi then writes on paper an equally cryptic message.
 
#+begin_quote
"Words of divine consciousness: moral exaltion; lasting feelings of elevation, elation, joy; a quickening of the moral sense, which strikes one as more important than an intellectual understanding of things; an alignment of the universe along moral lines, not intellectual ones; a realization that the founding principle of existence is what we call love, which works itself out sometimes not clearly, not cleanly, not immediately, nonetheless ineluctably. [...] An intellect confounded yet a trusting sense of presence and of ultimate purpose" (21.2,4).
#+end_quote

The paragraph seems to describe religion and a more moral, emotional view as opposed to a scientific or intellectual view. I am not fully sure what these words mean or how they relate to the story.
