* Chapter 4
  The main character describes the formation of Zootown (also a name mentioned earlier in the Author's Note) due to Pondicherry entering the Union of India on November 1, 1954. The zoo was expansive and had a variety of wildlife.

  Piscine mentions that, before the family moved to Pondicherry, his father used to work as a hotel owner in Madras. It is also revealed that the name of Piscine's father is Santosh Patel.

  Piscine had fond memories of playing around in the zoo, seeing an exotic array of animals.

  *Perhaps Piscine's love of animals contributed to his eventual pursuing of zoology from Chapter 1?*

  Then, Piscine laments about the uneducated criticism zoos receive for "taking away the freedom" of the animals, which would supposedly be better off in the wild. He goes on to explain how this is not the case and living in the wild brings about constant pressure for survival. Animals are quite conservative and bothered by the smallest changes in their environment. Pisicne briefly relates this misunderstanding to religion and God.

  The chapter ends with an explanation that the Pondicherry Zoo was filled in and discontinued.
