* Chapter 1
  The main character attended the University of Toronto, majoring in both religious studies and zoology. For his zoology thesis, they chose to study the three-toed sloth.

  One interesting point is that he said:
  #+begin_quote
  "I chose the sloth because its demeanour---calm, quiet, and introspective---did something to soothe my shattered self" (1.2).
  #+end_quote
  Coupled with the quote at the start of the chapter (seen below), it seems that the main character was unhappy with their life, only having religion and their interest in zoology.
  #+begin_quote
  "My suffering left me sad and gloomy" (1.1).
  #+end_quote
  The main character then goes on to explain certain findings of the three-toed sloth, being very truant and lazy, living in harmony with nature. The main character relates this to his belief of God.

  Being a relatively good and prestigious student, the main character received awards and got along with his scientific peers, despite them being atheistic.
  The main character comments little on his working life, only saying this:
  #+begin_quote
  "I have nothing to say of my working life, only that a tie is a noose, and inverted though it is, it wil hang a man nonetheless if he's not careful" (1.12).
  #+end_quote
  *Perhaps the main character has a somewhat unstable job or one that he has to carefully tread in?*

  The speaker then laments a little, feeling homesick for his town in Pondicherry, India, but also reaffirms his love for Canada and how he would rather stay.

  He then mentions that a certain man, _Richard Parker_, stayed with him and that he misses him, seeing him in his dreams and nightmares. Richard Parker seems to have suddenly abandoned the speaker at some point in the past.

  Abruptly, the setting seems to switch, with the speaker mentioning their time in a hospital in Mexico and the positive experience he had. The speaker was practically on the brink of death, barely able to walk with nausea and dizziness.

  *What caused the main character to end up in the state? The events of the story? Why the sudden time leap?*

  Next, the setting equally abruptly warps back to Canada, where the speaker laments how he was criticized for eating using his hands in an Indian restaurant.
